[tool.ruff]
extend-select = ['W',
                'C901',
                'I',
                'N',
                'YTT',
                'ANN',
                'S',
                'BLE',
                'B',
                'A',
                'C4',
                'ICN',
                'INP',
                'PIE',
                'T20',
                'PT',
                'Q',
                'RSE',
                'RET',
                'SLF',
                'SIM',
                'TID',
                'ARG',
                'PGH',
                'TRY',
                'NPY',
                'RUF',
                #'PTH'
                ]
target-version = 'py38'
ignore = ['TRY003', 'ANN101', 'ANN401', 'ANN102', 'ANN003'] # , , 'TRY003', 'RET505', , 'RET506']
exclude = ['tests', 'scripts', 'docs']
line-length=120

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
"*/tests/*" = ['S101']

[tool.pytest.ini_options]
markers = [
    "prefect_test: a test that integrates with Prefect",
    "regression: a regression test, likely slow",
]
